<?php

declare(strict_types=1);

namespace App\Services\DocumentConversion\Extractors;

use App\Contracts\DocumentExtractorInterface;
use App\DTOs\DocumentContent;
use App\DTOs\DocumentMetadata;
use Exception;
use Illuminate\Support\Facades\Log;
use Smalot\PdfParser\Config;
use Smalot\PdfParser\Parser;

final class PdfExtractor implements DocumentExtractorInterface
{
    private const array SUPPORTED_MIMES = [
        'application/pdf',
    ];

    /**
     * Patterns pour ignorer les éléments non désirés
     */
    private const array IGNORED_PATTERNS = [
        '/^Page \d+/i',
        '/^- \d+ -$/',
        '/^Page \d+ of \d+/i',
        '/^Copyright/i',
        '/^Confidential/i',
        '/^www\./i',
        '/^http[s]?:\/\//i',
        '/^\d{1,2}\/\d{1,2}\/\d{4}$/',
        '/^\d{4}-\d{2}-\d{2}$/',
        '/^Powered by/i',
        '/^Generated by/i',
        '/^Table of Contents/i',
        '/^Acknowledgements?/i',
        '/^Bibliography/i',
        '/^References/i',
    ];

    public function supports(string $filePath): bool
    {
        $mimeType = mime_content_type($filePath);

        return in_array($mimeType, self::SUPPORTED_MIMES, true);
    }

    public function extract(string $filePath, array $options = []): DocumentContent
    {
        try {
            $config = app(Config::class);
            $config->setDataTmFontInfoHasToBeIncluded(true);
            $parser = new Parser([], $config);

            $document = $parser->parseFile($filePath);

            $metadata = $this->extractMetadata($document);

            $rawText = $this->extractTextFromPages($document, $options);

            $rawText = $this->ensureUtf8Encoding($rawText);

            $cleanedText = $this->cleanText($rawText, $options);

            $options['filePath'] = $filePath;

            $content = new DocumentContent(
                rawText: $cleanedText,
                metadata: $metadata,
                options: $options,
            );

            Log::info('PDF extracted successfully', [
                'file' => $filePath,
                'pages' => $metadata->pageCount,
                'text_length' => mb_strlen($cleanedText),
                'first_page_skipped' => $options['skipFirstPage'] ?? false,
            ]);

            return $content;

        } catch (Exception $e) {
            Log::error('Error extracting PDF', [
                'file' => $filePath,
                'error' => $e->getMessage(),
            ]);

            throw new Exception('Erreur lors de l\'extraction du PDF: '.$e->getMessage());
        }
    }

    public function getSupportedMimeTypes(): array
    {
        return self::SUPPORTED_MIMES;
    }

    private function extractMetadata($document): DocumentMetadata
    {
        $details = $document->getDetails();

        return new DocumentMetadata(
            title: $details['Title'] ?? null,
            author: $details['Author'] ?? null,
            subject: $details['Subject'] ?? null,
            creator: $details['Creator'] ?? null,
            producer: $details['Producer'] ?? null,
            creationDate: $details['CreationDate'] ?? null,
            modificationDate: $details['ModDate'] ?? null,
            pageCount: count($document->getPages()),
        );
    }

    private function extractTextFromPages($document, array $options): string
    {
        $pages = $document->getPages();
        $skipFirstPage = $options['skipFirstPage'] ?? false;
        $textParts = [];

        foreach ($pages as $pageNumber => $page) {
            if ($skipFirstPage && $pageNumber === 0) {
                continue;
            }

            $pageText = $page->getText();
            if (! empty(mb_trim($pageText))) {
                $textParts[] = $pageText;
            }
        }

        return implode("\n\n", $textParts);
    }

    private function ensureUtf8Encoding(string $text): string
    {
        // If already valid UTF-8, skip conversion entirely — avoids destroying valid accented chars
        if (mb_check_encoding($text, 'UTF-8')) {
            return $this->fixEncodingIssues($text);
        }

        // Prefer Windows-1252 over ISO-8859-1: it's a strict superset covering French PDFs from Windows
        $encoding = mb_detect_encoding($text, ['Windows-1252', 'ISO-8859-1', 'ASCII'], true);
        if ($encoding) {
            $text = mb_convert_encoding($text, 'UTF-8', $encoding);

            return $this->fixEncodingIssues($text);
        }

        // ISO-8859-1 / Latin-1 is lossless for every byte value (0x00–0xFF → valid codepoint)
        $text = mb_convert_encoding($text, 'UTF-8', 'ISO-8859-1');

        return $this->fixEncodingIssues($text);
    }

    /**
     * Corrige les problèmes d'encodage courants dans les PDFs.
     *
     * Règles de conservation :
     * - «»        guillemets français         → conservés (typographie française)
     * - " "       guillemets anglais typogr.  → conservés
     * - – (U+2013) tiret demi-cadratin        → conservé (plages, dialogue)
     * - — (U+2014) tiret cadratin             → conservé (incises, dialogue français)
     * - − (U+2212) signe moins mathématique   → conservé
     */
    private function fixEncodingIssues(string $text): string
    {
        // Octets nuls : fréquents dans les PDFs encodés en UTF-16 interne
        $text = str_replace("\x00", '', $text);

        $replacements = [
            // Ligatures typographiques → séquences ASCII équivalentes
            "\xEF\xAC\x81" => 'fi',   // ﬁ
            "\xEF\xAC\x82" => 'fl',   // ﬂ
            "\xEF\xAC\x80" => 'ff',   // ﬀ
            "\xEF\xAC\x83" => 'ffi',  // ﬃ
            "\xEF\xAC\x84" => 'ffl',  // ﬄ
            "\xEF\xAC\x85" => 'ft',   // ﬅ
            "\xEF\xAC\x86" => 'st',   // ﬆ

            // Apostrophes typographiques → apostrophe standard
            "\xE2\x80\x98" => "'",  // U+2018 '
            "\xE2\x80\x99" => "'",  // U+2019 '

            // Guillemets bas typographiques
            "\xE2\x80\x9A" => ',',   // U+201A ‚ virgule basse simple
            "\xE2\x80\x9E" => '"',   // U+201E „ guillemet bas double

            // Ellipse typographique → trois points ASCII
            "\xE2\x80\xA6" => '...',  // U+2026 …

            // Tiret conditionnel (césure PDF) → supprimé pour réunir les mots
            "\xC2\xAD" => '',  // U+00AD soft hyphen

            // Espaces spéciales → espace ordinaire
            "\xC2\xA0" => ' ',  // U+00A0 espace insécable
            "\xE2\x80\xAF" => ' ',  // U+202F espace fine insécable
            "\xE2\x80\x82" => ' ',  // U+2002 en space
            "\xE2\x80\x83" => ' ',  // U+2003 em space

            // Caractère de remplacement Unicode
            "\xEF\xBF\xBD" => '',   // U+FFFD
        ];

        return str_replace(array_keys($replacements), array_values($replacements), $text);
    }

    /**
     * Nettoie le texte extrait
     */
    private function cleanText(string $text, array $options): string
    {
        $lines = explode("\n", $text);
        $cleanedLines = [];
        $consecutiveEmptyLines = 0;

        foreach ($lines as $line) {
            $line = mb_trim($line);

            if (empty($line)) {
                $consecutiveEmptyLines++;
                if ($consecutiveEmptyLines <= 1) {
                    $cleanedLines[] = '';
                }

                continue;
            }

            $consecutiveEmptyLines = 0;

            if (mb_strlen($line) < 3 && ! $this->isImportantShortLine($line)) {
                continue;
            }

            if ($this->shouldIgnoreLine($line, $options)) {
                continue;
            }

            $cleanedLines[] = $line;
        }

        return implode("\n", $cleanedLines);
    }

    /**
     * Vérifie si une ligne courte doit être conservée malgré sa longueur.
     * Utilise des catégories Unicode pour supporter les caractères accentués (français, etc.).
     */
    private function isImportantShortLine(string $line): bool
    {
        // Les chiffres seuls sont traités comme numéros de page → ignorés
        if (preg_match('/^\d+$/', $line)) {
            return false;
        }

        // Conserver les courtes lignes contenant des lettres, chiffres ou ponctuation
        // \pP = toute ponctuation Unicode (virgule, point, !, ?, :, ;, guillemets…)
        return (bool) preg_match('/^[\pL\pN\pP\s]{1,3}$/u', $line);
    }

    private function shouldIgnoreLine(string $line, array $options): bool
    {
        if ($options['ignorePageNumbers'] ?? true) {
            if ($this->isPageNumber($line)) {
                return true;
            }
        }

        foreach (self::IGNORED_PATTERNS as $pattern) {
            if (preg_match($pattern, $line)) {
                return true;
            }
        }

        return false;
    }

    private function isPageNumber(string $line): bool
    {
        return preg_match('/^(Page\s+)?\d+(\s+of\s+\d+)?$/i', $line) ||
            preg_match('/^-\s*\d+\s*-$/', $line) ||
            (preg_match('/^\d+$/', $line) && mb_strlen($line) <= 3);
    }
}
